export const GET_ERRORS = "GET_ERRORS";

export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_DATA = "SET_USER_DATA";

export const SET_HOUSE_DATA = "SET_HOUSE_DATA";
export const SET_CURRENT_HOUSE = "SET_CURRENT_HOUSE";